project:
  type: website
  output-dir: docs

website:
  title: "Amilcar Campos"
  favicon: "images/profile.png"
  
  page-footer:
    center: |
        [Contact Amilcar Campos](mailto:contacto@amicampos.com)
    left: |
        Website Made with [Quarto](https://quarto.org/)
    right: |
        [Github Code Repo](https://github.com/AmiCM)
    background: "#2780e3"

  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: blog.qmd
        text: Blog
    right:
      - icon: envelope
        text: Contact me
        href: mailto::contacto@amicampos.com
      - icon: github
        href: https://github.com/AmiCM/
      - icon: linkedin
        href: https://www.linkedin.com/in/amilcar-campos-mena-0275701a3/
      - icon: twitter
        href: https://twitter.com/Amilcar68669582/
    
format:
  html:
    theme: 
      light: litera
      dark: superhero
    css: styles.css

editor: visual

